In [1]:
from __future__ import print_function
import torch

In [2]:
torch.__version__

'1.6.0+cpu'

In [3]:
a = torch.empty(6,3)
print(a)

tensor([[-2.2577e-27,  8.0014e-43, -2.2577e-27],
        [ 8.0014e-43, -1.0465e-26,  8.0014e-43],
        [-1.0477e-26,  8.0014e-43, -1.0859e-26],
        [ 8.0014e-43, -5.6021e-27,  8.0014e-43],
        [-5.5999e-27,  8.0014e-43, -5.5999e-27],
        [ 8.0014e-43, -1.0850e-26,  8.0014e-43]])


In [4]:
a = torch.rand(4,3)
print(a)

tensor([[0.7945, 0.0252, 0.7739],
        [0.6521, 0.0206, 0.2088],
        [0.6202, 0.7565, 0.3125],
        [0.2163, 0.4197, 0.8613]])


In [5]:
a = torch.zeros(4,3, dtype=torch.long)
print(a)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
#torch expects always numerical values but not strings
a = torch.tensor([7.8,5])
type(a)

torch.Tensor

In [8]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
a

tensor([7.8000, 5.0000])

In [14]:
#override the previous ize of the tensors
a=a.new_ones(5,5, dtype = torch.double)
print(a)

a = torch.randn_like(a, dtype = torch.float)
print(a)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)
tensor([[ 2.4825,  0.0905,  0.6765, -0.0592,  0.5039],
        [-1.0823, -0.3050, -1.0890, -1.4767, -1.5256],
        [-0.4688,  0.2568,  0.0660,  1.0743, -0.2290],
        [ 0.4706, -0.0541,  0.2365, -0.5373, -0.9655],
        [ 0.0945,  2.0391,  0.5677,  0.8686,  1.8126]])


In [15]:
b = torch.randn(5,5)
print(a+b)

tensor([[ 5.3566,  0.9450,  0.6516, -0.4599, -0.3498],
        [-1.2579, -0.8106, -2.0951, -0.8258, -2.4736],
        [-0.9787, -0.0728,  1.3333,  0.3574,  1.0224],
        [ 1.0329, -0.6899, -0.6708,  0.1706, -0.6920],
        [ 1.6122,  1.1947,  1.1040,  0.1058,  1.9891]])


In [18]:
result = torch.empty(5,5)
torch.add(a,b, out=result)
print(result)

tensor([[ 5.3566,  0.9450,  0.6516, -0.4599, -0.3498],
        [-1.2579, -0.8106, -2.0951, -0.8258, -2.4736],
        [-0.9787, -0.0728,  1.3333,  0.3574,  1.0224],
        [ 1.0329, -0.6899, -0.6708,  0.1706, -0.6920],
        [ 1.6122,  1.1947,  1.1040,  0.1058,  1.9891]])


In [19]:
b.add_(a)
print(b)

tensor([[ 5.3566,  0.9450,  0.6516, -0.4599, -0.3498],
        [-1.2579, -0.8106, -2.0951, -0.8258, -2.4736],
        [-0.9787, -0.0728,  1.3333,  0.3574,  1.0224],
        [ 1.0329, -0.6899, -0.6708,  0.1706, -0.6920],
        [ 1.6122,  1.1947,  1.1040,  0.1058,  1.9891]])


In [20]:
a[0][1]

tensor(0.0905)

In [21]:
a[:,2]

tensor([ 0.6765, -1.0890,  0.0660,  0.2365,  0.5677])

In [22]:
a = torch.randn(3,3)
b = a.view(9)
c = a.view(-1,9)

In [23]:
print(a.size(),b.size(),c.size())

torch.Size([3, 3]) torch.Size([9]) torch.Size([1, 9])


In [24]:
a = torch.randn(1)

In [25]:
a.item()

-0.9618174433708191

In [26]:
x = torch.ones(4)
x

tensor([1., 1., 1., 1.])

In [27]:
y = x.numpy()
type(y)

numpy.ndarray

In [28]:
x.add_(1)
print(x)
print(y)

tensor([2., 2., 2., 2.])
[2. 2. 2. 2.]


In [29]:
import numpy as np
f = np.ones(4)
g = torch.from_numpy(f)
np.add(f,3, out=f)
print(f)
print(g)

[4. 4. 4. 4.]
tensor([4., 4., 4., 4.], dtype=torch.float64)


In [30]:
type(g)

torch.Tensor

In [31]:
#let us run this cell only if CUDA is available
#we will use "torch.device" objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    y= torch.ones_like(x, device=device)
    x=x.to(device)
    z= x + y
    print(z)
    print(z.to("cpu", torch.double))

# AUTOGRAD: Automatic Differentiation

In [32]:
import torch

In [33]:
a = torch.ones(2,2, requires_grad=True)
print(a)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [35]:
b = a+2
print(b)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [36]:
print(b.grad_fn)

In [37]:
c = b * b * 3
out = c.mean()
print(c, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [39]:
p=torch.rand(3,3)
p = ((p*3)/(p-1))
print(p.requires_grad)
p.requires_grad_(True)
print(p.requires_grad)
q = (p*p).sum()
print(q.grad_fn)

False
True


# Gradient

In [41]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [42]:
out.backward()

In [44]:
out.grad

C:\Users\rkocherlakota\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  """Entry point for launching an IPython kernel.


In [45]:
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [47]:
a.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [48]:
x = torch.randn(3, requires_grad= True)
y = x*2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([  15.5942, -596.5112,  973.8916], grad_fn=<MulBackward0>)


In [49]:
v = torch.tensor([0.1,1.0,0.001], dtype = torch.float)
y.backward(v)

print(x.grad)

tensor([ 204.8000, 2048.0000,    2.0480])


In [50]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class network(nn.Module):
    
    def __init__(self):
        super(network,self).__init__()
        #1 input image channel, 6 output channels and 3X3 square convolution kernel
        self.conv1 = nn.Conv2d(1,6,3)
        self.conv2 = nn.Conv2d(6,16,3)
        #an affine operation: y= mx+c
        self.fc1 = nn.Linear(16*6*6,120)
        self.fc2 = nn.Linear(120,84)
        self.fc3 = nn.Linear(84,10)
    
    def forward(self,x):
        #Max pooling layer of size (2,2)
        x = F.max_pool2d(F.relu(self.conv1(x)),(2,2))
        #if size is a square you only specify a single number 
        x = F.max_pool2d(F.relu(self.conv2(x)),2)
        x = x.view(-1,self.num_flat_features(x)) #reset the values by flattening
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self,x):
        size = x.size()[1:] #all dimensions except batch dimension
        num_features = 1
        for s in size:
            num_features*=s
        return num_features

net = network()            
print(net)        

network(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [53]:
params = list(net.parameters())
print(params)

[Parameter containing:
tensor([[[[ 0.0055,  0.2000,  0.2227],
          [-0.0233,  0.0025,  0.0775],
          [-0.0191,  0.0964, -0.2992]]],


        [[[-0.2746,  0.1286, -0.0219],
          [-0.1913, -0.0352,  0.0271],
          [ 0.2517,  0.1299, -0.2052]]],


        [[[ 0.2534,  0.2669, -0.3150],
          [-0.0830, -0.1725, -0.2842],
          [-0.0925, -0.0426, -0.1237]]],


        [[[-0.0815, -0.1028,  0.2731],
          [-0.3222,  0.0144, -0.0516],
          [ 0.1708, -0.2629, -0.1537]]],


        [[[ 0.1882,  0.2756, -0.1468],
          [ 0.1427, -0.2444,  0.0314],
          [ 0.0844, -0.2161, -0.1978]]],


        [[[ 0.2675,  0.2284, -0.2823],
          [ 0.0531, -0.2239, -0.0448],
          [ 0.2196,  0.0672,  0.0828]]]], requires_grad=True), Parameter containing:
tensor([-0.1506,  0.0569,  0.0781,  0.0129,  0.3285,  0.2143],
       requires_grad=True), Parameter containing:
tensor([[[[-6.7017e-02,  8.0972e-02, -1.6347e-02],
          [ 2.3753e-02, -1.7492e-02,  9.1682e

In [55]:
print(len(params))
print(params[0].size())

10
torch.Size([6, 1, 3, 3])


In [57]:
s = list(net.parameters())

In [59]:
s[0].size()

torch.Size([6, 1, 3, 3])

In [60]:
s[1].size()

torch.Size([6])

In [61]:
s[2].size()

torch.Size([16, 6, 3, 3])

In [62]:
s[3].size()

torch.Size([16])

In [63]:
s[4].size()

torch.Size([120, 576])

In [64]:
s[5].size()

torch.Size([120])

In [65]:
s[6].size()

torch.Size([84, 120])

In [66]:
s[7].size()

torch.Size([84])

In [67]:
s[8].size()

torch.Size([10, 84])

In [68]:
s[9].size()

torch.Size([10])

In [70]:
inp = torch.randn(1,1,32,32)
out = net(inp)
print(out)

tensor([[ 0.0670,  0.0194, -0.0648,  0.1775,  0.0317, -0.0163,  0.0256, -0.1010,
         -0.0276,  0.0469]], grad_fn=<AddmmBackward>)


In [73]:
net.zero_grad()
out.backward(torch.randn(1,10))

In [75]:
output = net(inp)
target = torch.randn(10)
target = target.view(1,-1)
criterion = nn.MSELoss()

loss = criterion(output,target)
print(loss)

tensor(1.2896, grad_fn=<MseLossBackward>)


In [76]:
print(loss.grad_fn)
print(loss.grad_fn.next_functions[0][0]) #linear
print(loss.grad_fn.next_functions[0][0].next_functions[0][0]) #relu

# Updating the weights

In [77]:
learning_rate = 0.01
for f in net.parameters():
    f.data.sub_(f.grad.data * learning_rate)

In [79]:
import torch.optim as optim

#create your optimizer
optimizer = optim.SGD(net.parameters(), lr = 0.01)

#in your training loop
optimizer.zero_grad()
output = net(inp)
loss = criterion(output,target)
loss.backward()
optimizer.step() #updates the weight

In [80]:
loss

tensor(1.2671, grad_fn=<MseLossBackward>)

In [81]:
optimizer

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.01
    momentum: 0
    nesterov: False
    weight_decay: 0
)